package store

// builtinSuites is the seed question bank shipped with the migration. Each
// suite carries 12 cases across three difficulty tiers (4 basic, 4
// intermediate, 4 hard). Rule cases stay deterministic; judge cases probe
// open-ended ability. gen 1 cases are the original bank (kept verbatim so
// existing deployments recognize them); gen 2 cases are the tiered expansion
// added by ticket 21.
var builtinSuites = []seedSuite{
	{
		key:  "basic",
		name: "基础指令遵循",
		cases: []seedCase{
			{
				gen: 1, difficulty: "basic",
				prompt:       "只回复 pong 这个单词",
				verdictType:  "rule",
				ruleMode:     strptr("contains"),
				ruleExpected: strptr("pong"),
			},
			{
				gen: 1, difficulty: "basic",
				prompt:       "用严格的 JSON 回复 {\"ok\": true}，不要任何其他文字",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`^\s*\{\s*"ok"\s*:\s*true\s*\}\s*$`),
			},
			{
				gen: 1, difficulty: "basic",
				prompt:       "数到 3，每行一个数字",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`^1\s*\n2\s*\n3\s*$`),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:       "只回复单词 hello，不要任何标点",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("hello"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "把「人工智能」翻译成英文，只回复翻译结果",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`(?i)artificial intelligence`),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "用一句话解释什么是递归，回答中必须包含「自己」两个字",
				verdictType:  "rule",
				ruleMode:     strptr("contains"),
				ruleExpected: strptr("自己"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "把数字 42 转成中文大写，只回复结果",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("四十二"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "重复我说的话：「天气真好」，只回复这句话",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("天气真好"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "只输出 1 到 5 中所有偶数，用英文逗号分隔，不要其他内容",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("2,4"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "把「hello world」每个单词首字母大写，只回复结果",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("Hello World"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "计算 3+4*2 并只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("11"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "将字符串「abcdef」反转，只回复结果",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("fedcba"),
			},
		},
	},
	{
		key:  "reasoning",
		name: "推理数学",
		cases: []seedCase{
			{
				gen: 1, difficulty: "basic",
				prompt:       "17 + 25 = ? 只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("42"),
			},
			{
				gen: 1, difficulty: "intermediate",
				prompt:       "一个班里 30 人，18 人会游泳，15 人会骑车，至少几人两样都会？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("3"),
			},
			{
				gen: 1, difficulty: "basic",
				prompt:       "数列 1, 1, 2, 3, 5, 8 的下一个数字是什么？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("13"),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:       "100 以内最大的质数是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("97"),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:       "7 的平方是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("49"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "一个数乘以 3 等于 51，这个数是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("17"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "鸡兔同笼，共 10 个头、28 条腿，鸡有几只？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("6"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "一本书 120 页，第一天读了 1/4，还剩多少页？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("90"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "等差数列 2, 5, 8, 11 的第 10 项是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("29"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "某商品先涨价 10% 再降价 10%，现价是原价的百分之几？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("99"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "log2(64) 等于多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("6"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "从 5 个人中选 2 个人，有多少种选法？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("10"),
			},
		},
	},
	{
		key:  "coding",
		name: "代码能力",
		cases: []seedCase{
			{
				gen: 1, difficulty: "basic",
				prompt:       "用 Python 写一个函数 add(a, b)，只回复代码",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`def\s+add\s*\(`),
			},
			{
				gen: 1, difficulty: "basic",
				prompt:       "下面代码的输出是什么，只回复数字： print(len([1,2,3])*2)",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("6"),
			},
			{
				gen: 1, difficulty: "intermediate",
				prompt:       "Python 表达式 'hello'[1] 的结果是什么？只回复这个字符",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("e"),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:       "Python 中 2 ** 10 的结果是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("1024"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "下面 Python 代码的输出是什么，只回复结果：print('ab' * 3)",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("ababab"),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "用 Python 写一个判断偶数的函数 is_even(n)，只回复代码",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`def\s+is_even\s*\(`),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:       "下面 JavaScript 代码的输出是什么，只回复数字：console.log([1,2,3].map(x => x * 2).length)",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("3"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "Python 表达式 sorted([3,1,2])[0] 的结果是什么？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("1"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "下面 Python 代码的输出是什么，只回复结果：print(','.join(['a','b','c']))",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("a,b,c"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "用 Python 写一个函数 reverse_string(s) 返回反转后的字符串，只回复代码",
				verdictType:  "rule",
				ruleMode:     strptr("regex"),
				ruleExpected: strptr(`def\s+reverse_string\s*\(`),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "Python 中 list(range(5)) 所有元素的和是多少？只回复数字",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("10"),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:       "下面 Python 代码的输出是什么，只回复数字：print(len({'a':1,'b':2}))",
				verdictType:  "rule",
				ruleMode:     strptr("exact"),
				ruleExpected: strptr("2"),
			},
		},
	},
	{
		key:  "chinese",
		name: "中文能力",
		cases: []seedCase{
			{
				gen: 1, difficulty: "basic",
				prompt:      "用一句中文总结'亡羊补牢'的寓意",
				verdictType: "judge",
				rubric:      strptr("评估作答是否用一句中文准确总结了'亡羊补牢'的寓意（出了问题之后及时补救，仍然可以避免更大的损失）。完全准确 1 分，部分准确 0.5 分，错误或偏离 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 1, difficulty: "intermediate",
				prompt:      "把「他今天没来上班，因为生病了」改写成更正式的表达，只回复改写后的句子",
				verdictType: "judge",
				rubric:      strptr("评估改写是否满足两点：1) 表达更正式（书面语，如「因身体不适今日未能到岗」）；2) 保留原意。两点都满足 1 分，只满足一点 0.5 分，都不满足 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 1, difficulty: "basic",
				prompt:      "「画蛇添足」这个成语是什么意思？用一句中文回答",
				verdictType: "judge",
				rubric:      strptr("评估作答是否用一句中文准确解释了'画蛇添足'（做了多余的事，反而坏了事）。完全准确 1 分，部分准确 0.5 分，错误或偏离 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:      "用一句中文解释「守株待兔」的意思",
				verdictType: "judge",
				rubric:      strptr("评估作答是否用一句中文准确解释了「守株待兔」（心存侥幸，妄想不付出努力就得到收获）。完全准确 1 分，部分准确 0.5 分，错误或偏离 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "basic",
				prompt:      "写一句关于春天的中文句子",
				verdictType: "judge",
				rubric:      strptr("评估作答是否是一句通顺的中文且内容确实描写春天。通顺且切题 1 分，通顺但偏离春天 0.5 分，不通顺或非中文 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:      "把「低碳生活，从我做起」扩展成 50 字左右的一段中文",
				verdictType: "judge",
				rubric:      strptr("评估扩写是否满足两点：1) 围绕低碳生活的主题且内容具体；2) 篇幅约 50 字、语句通顺。两点都满足 1 分，只满足一点 0.5 分，都不满足 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:      "用一句中文概括「塞翁失马，焉知非福」的道理",
				verdictType: "judge",
				rubric:      strptr("评估作答是否用一句中文准确概括了「塞翁失马，焉知非福」的道理（坏事在一定条件下可能变成好事，反之亦然，不必为一时的得失过分悲喜）。完全准确 1 分，部分准确 0.5 分，错误或偏离 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "intermediate",
				prompt:      "将「The quick brown fox jumps over the lazy dog」翻译成中文，只回复译文",
				verdictType: "judge",
				rubric:      strptr("评估译文是否满足两点：1) 准确传达原句意思（敏捷的棕色狐狸跳过懒狗）；2) 中文通顺自然。两点都满足 1 分，只满足一点 0.5 分，都不满足 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:      "写一首四句的中文短诗，主题是秋天",
				verdictType: "judge",
				rubric:      strptr("评估诗作是否满足三点：1) 恰好四句；2) 中文且语句有诗意；3) 紧扣秋天主题并含有具体意象。三点都满足 1 分，满足两点 0.5 分，其余 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:      "用中文写一段 80 字左右的产品介绍，产品是一把雨伞",
				verdictType: "judge",
				rubric:      strptr("评估产品介绍是否满足三点：1) 围绕雨伞展开；2) 有卖点表达（如便携、防晒、抗风）；3) 篇幅约 80 字、中文通顺。三点都满足 1 分，满足两点 0.5 分，其余 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:      "分别用一句中文解释「内卷」和「躺平」",
				verdictType: "judge",
				rubric:      strptr("评估作答是否各用一句中文准确解释了两个词：「内卷」（非理性的过度内部竞争，投入增加但收益不增）；「躺平」（主动降低欲望、退出过度竞争的生活态度）。两个都准确 1 分，只准确一个 0.5 分，都不准确 0 分。" + judgeRubricSuffix),
			},
			{
				gen: 2, difficulty: "hard",
				prompt:      "用一句中文反驳「读书无用论」",
				verdictType: "judge",
				rubric:      strptr("评估作答是否满足两点：1) 明确反驳「读书无用论」的立场；2) 给出有说服力的理由（如读书提升认知、拓宽选择、长期回报）。两点都满足 1 分，只满足一点 0.5 分，都不满足 0 分。" + judgeRubricSuffix),
			},
		},
	},
}
